version: '3.8'

services:
  mariadb:
    image: statesflow/partiel-app-mariadb:latest
    container_name: mariadb-server
    environment:
      MYSQL_ROOT_PASSWORD: adminpassword
      MYSQL_DATABASE: partielDatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: adminpassword
    volumes:
      - mariadb_data:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "3307:3306"
    networks:
      - partiel-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  flask:
    image: statesflow/partiel-app-flask:latest
    container_name: flask-partiel
    environment:
      - FLASK_ENV=development
      - DATABASE_HOST=mariadb
      - DATABASE_PORT=3306
      - DATABASE_USER=admin
      - DATABASE_PASSWORD=adminpassword
      - DATABASE_NAME=partielDatabase
    ports:
      - "5001:5000"
    depends_on:
      - mariadb
    networks:
      - partiel-network
    healthcheck:
      test: ["CMD-SHELL", "curl -X GET", "http://localhost:5001/api/messages"]
      interval: 10s
      timeout: 5s
      retries: 3

  vuejs:
    image: statesflow/partiel-app-vuejs:latest
    container_name: vuejs-partiel
    ports:
      - "80:80"
    depends_on:
      - flask
    networks:
      - partiel-network
    healthcheck:
      test: ["CMD-SHELL", "curl --fail", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  mariadb_data:
    name: partiel_mariadb_data  

networks:
  partiel-network:
    name: partiel-network
    driver: bridge